[package]
name = "gurls"
version = "0.0.1"
edition = "2021"
description = "Gear URL Shortener (GURLS)"
license = "MIT"

[lib]
name = "gurls"
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git" }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }
